<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Quiz;
use App\Models\Module;

class QuizSeeder extends Seeder
{
    public function run(): void
    {
        $modules = Module::orderBy('id')->get();
        if ($modules->count() < 3) {
            return; // Needs 3 modules
        }

        $m1 = $modules[0]->id;
        $m2 = $modules[1]->id;
        $m3 = $modules[2]->id;

        $questions = [
            // Modul 1
            ['module_id' => $m1, 'question' => 'Apa fungsi utama dari tag <nav> pada HTML5?', 'option_a' => 'Membuat teks menjadi miring (italic).', 'option_b' => 'Mendefinisikan bagian halaman yang berisi tautan navigasi utama.', 'option_c' => 'Menampilkan gambar dengan format yang responsif.', 'option_d' => 'Membuat baris baru pada teks (line break).', 'correct_answer' => 'B'],
            ['module_id' => $m1, 'question' => 'Properti CSS manakah yang tepat digunakan untuk mengubah warna latar belakang dari sebuah card (kotak)?', 'option_a' => 'color', 'option_b' => 'bgcolor', 'option_c' => 'background-color', 'option_d' => 'back-color', 'correct_answer' => 'C'],
            ['module_id' => $m1, 'question' => 'Atribut wajib apa yang harus ada di dalam tag <a> agar tautan dapat mengarahkan user ke halaman lain?', 'option_a' => 'src', 'option_b' => 'href', 'option_c' => 'link', 'option_d' => 'target', 'correct_answer' => 'B'],
            ['module_id' => $m1, 'question' => 'Dalam CSS, simbol apa yang digunakan di awal nama untuk menargetkan sebuah class HTML (misalnya: class="kotak-bento")?', 'option_a' => '# (Hashtag)', 'option_b' => '* (Bintang)', 'option_c' => '. (Titik)', 'option_d' => '@ (At)', 'correct_answer' => 'C'],
            ['module_id' => $m1, 'question' => 'Kepanjangan dari HTML adalah...', 'option_a' => 'HyperText Markup Language', 'option_b' => 'HyperLinks and Text Markup Language', 'option_c' => 'Home Tool Markup Language', 'option_d' => 'Hyper Tool Markup Language', 'correct_answer' => 'A'],
            ['module_id' => $m1, 'question' => 'Tag HTML apa yang digunakan untuk membuat judul (heading) utama yang ukurannya paling besar pada sebuah halaman web?', 'option_a' => '<header>', 'option_b' => '<h6>', 'option_c' => '<title>', 'option_d' => '<h1>', 'correct_answer' => 'D'],
            ['module_id' => $m1, 'question' => 'Untuk membuat daftar yang tidak berurutan (menggunakan bullet points) di HTML, tag apa yang tepat untuk digunakan?', 'option_a' => '<ol>', 'option_b' => '<ul>', 'option_c' => '<li>', 'option_d' => '<dl>', 'correct_answer' => 'B'],
            ['module_id' => $m1, 'question' => 'Di dalam semantik HTML5, tag manakah yang paling tepat untuk membungkus konten utama dari sebuah dokumen web?', 'option_a' => '<div>', 'option_b' => '<main>', 'option_c' => '<section>', 'option_d' => '<article>', 'correct_answer' => 'B'],
            ['module_id' => $m1, 'question' => 'Kepanjangan dari CSS adalah...', 'option_a' => 'Cascading Style Sheets', 'option_b' => 'Computer Style Sheets', 'option_c' => 'Creative Style System', 'option_d' => 'Colorful Style Sheets', 'correct_answer' => 'A'],
            ['module_id' => $m1, 'question' => 'Bagaimana cara yang benar untuk menghubungkan file CSS eksternal (misalnya style.css) ke dalam dokumen HTML?', 'option_a' => '<style src="style.css">', 'option_b' => '<css link="style.css">', 'option_c' => '<link rel="stylesheet" href="style.css">', 'option_d' => '<script src="style.css"></script>', 'correct_answer' => 'C'],
            ['module_id' => $m1, 'question' => 'Tag HTML apa yang digunakan untuk menyisipkan gambar pada halaman web?', 'option_a' => '<picture>', 'option_b' => '<image>', 'option_c' => '<src>', 'option_d' => '<img>', 'correct_answer' => 'D'],
            ['module_id' => $m1, 'question' => 'Pada tag <img>, atribut apa yang sangat penting ditambahkan untuk memberikan teks alternatif jika gambar gagal dimuat atau untuk pembaca layar (screen reader)?', 'option_a' => 'title', 'option_b' => 'alt', 'option_c' => 'desc', 'option_d' => 'info', 'correct_answer' => 'B'],
            ['module_id' => $m1, 'question' => 'Properti CSS apa yang digunakan untuk mengubah ukuran font sebuah teks?', 'option_a' => 'text-size', 'option_b' => 'font-style', 'option_c' => 'text-style', 'option_d' => 'font-size', 'correct_answer' => 'D'],
            ['module_id' => $m1, 'question' => 'Jika kamu ingin membuat sebuah teks menjadi tebal (bold) menggunakan CSS, properti apa yang harus diatur?', 'option_a' => 'font-weight', 'option_b' => 'text-bold', 'option_c' => 'font-style', 'option_d' => 'text-decoration', 'correct_answer' => 'A'],
            ['module_id' => $m1, 'question' => 'Simbol apa yang digunakan di dalam CSS untuk menargetkan elemen berdasarkan atribut id?', 'option_a' => '. (Titik)', 'option_b' => '# (Hashtag)', 'option_c' => '* (Bintang)', 'option_d' => '& (Dan)', 'correct_answer' => 'B'],
            ['module_id' => $m1, 'question' => 'Tag HTML mana yang digunakan untuk menginisiasi pembuatan sebuah tabel?', 'option_a' => '<tbody>', 'option_b' => '<tr>', 'option_c' => '<table>', 'option_d' => '<td>', 'correct_answer' => 'C'],
            ['module_id' => $m1, 'question' => 'Di dalam elemen tabel HTML, tag apa yang digunakan untuk membuat sebuah baris (row) baru?', 'option_a' => '<tr>', 'option_b' => '<td>', 'option_c' => '<th>', 'option_d' => '<thead>', 'correct_answer' => 'A'],
            ['module_id' => $m1, 'question' => 'Tag semantik HTML5 apa yang digunakan untuk membungkus elemen-elemen di bagian paling bawah website (seperti informasi hak cipta atau kontak)?', 'option_a' => '<bottom>', 'option_b' => '<end>', 'option_c' => '<footer>', 'option_d' => '<base>', 'correct_answer' => 'C'],
            ['module_id' => $m1, 'question' => 'Pada CSS Box Model, properti margin digunakan untuk...', 'option_a' => 'Memberikan ruang kosong di dalam elemen (di antara konten dan border).', 'option_b' => 'Memberikan ruang kosong di luar elemen (mendorong elemen lain menjauh).', 'option_c' => 'Memberikan garis tepi pada elemen.', 'option_d' => 'Mengatur lebar maksimal sebuah elemen.', 'correct_answer' => 'B'],
            ['module_id' => $m1, 'question' => 'Sebaliknya, properti padding pada CSS Box Model digunakan untuk...', 'option_a' => 'Memberikan ruang kosong di dalam elemen (di antara konten dan border).', 'option_b' => 'Memberikan ruang kosong di luar elemen.', 'option_c' => 'Memberikan bayangan pada kotak.', 'option_d' => 'Mengatur tinggi elemen agar responsif.', 'correct_answer' => 'A'],
            ['module_id' => $m1, 'question' => 'Nilai display manakah pada CSS yang membuat sebuah elemen tidak mengambil seluruh lebar baris, melainkan membiarkan elemen lain berada di sebelahnya secara horizontal?', 'option_a' => 'block', 'option_b' => 'inline', 'option_c' => 'hidden', 'option_d' => 'grid', 'correct_answer' => 'B'],
            ['module_id' => $m1, 'question' => 'Tag HTML apa yang digunakan untuk membuat sebuah formulir (form) tempat user menginputkan data?', 'option_a' => '<input>', 'option_b' => '<form>', 'option_c' => '<fieldset>', 'option_d' => '<data>', 'correct_answer' => 'B'],
            ['module_id' => $m1, 'question' => 'Atribut pada tag <input> yang berfungsi menentukan jenis atau tipe inputan (seperti teks biasa, password, kotak centang, dll) adalah...', 'option_a' => 'name', 'option_b' => 'class', 'option_c' => 'type', 'option_d' => 'value', 'correct_answer' => 'C'],
            ['module_id' => $m1, 'question' => 'Bagaimana cara yang benar untuk menuliskan sebuah komentar (comment) di dalam file CSS?', 'option_a' => '// Ini komentar //', 'option_b' => '`Ini komentar`', 'option_c' => '/* Ini komentar */', 'option_d' => '\' Ini komentar', 'correct_answer' => 'C'],
            ['module_id' => $m1, 'question' => 'Properti CSS color berfungsi secara spesifik untuk mengatur...', 'option_a' => 'Warna teks', 'option_b' => 'Warna latar belakang', 'option_c' => 'Warna garis tepi (border)', 'option_d' => 'Warna bayangan', 'correct_answer' => 'A'],

            // Modul 2
            ['module_id' => $m2, 'question' => 'Manakah dari kata kunci berikut yang BUKAN cara yang valid untuk mendeklarasikan variabel di JavaScript modern?', 'option_a' => 'var', 'option_b' => 'let', 'option_c' => 'const', 'option_d' => 'define', 'correct_answer' => 'D'],
            ['module_id' => $m2, 'question' => 'Tipe data apa di JavaScript yang hanya memiliki dua kemungkinan nilai, yaitu true (benar) atau false (salah)?', 'option_a' => 'String', 'option_b' => 'Integer', 'option_c' => 'Boolean', 'option_d' => 'Array', 'correct_answer' => 'C'],
            ['module_id' => $m2, 'question' => 'Bagaimana cara mencetak pesan atau melakukan debugging untuk melihat nilai variabel ke dalam console browser?', 'option_a' => 'print("Pesan");', 'option_b' => 'console.log("Pesan");', 'option_c' => 'echo("Pesan");', 'option_d' => 'document.write("Pesan");', 'correct_answer' => 'B'],
            ['module_id' => $m2, 'question' => 'Simbol manakah yang digunakan untuk operator perbandingan "Sangat Sama / Strict Equality" (memeriksa nilai DAN tipe datanya) di JavaScript?', 'option_a' => '=', 'option_b' => '==', 'option_c' => '===', 'option_d' => '!=', 'correct_answer' => 'C'],
            ['module_id' => $m2, 'question' => 'Bagaimana penulisan sintaks yang benar untuk membuat komentar satu baris di JavaScript?', 'option_a' => '`Komentar`', 'option_b' => '// Komentar', 'option_c' => '/* Komentar */', 'option_d' => '# Komentar', 'correct_answer' => 'B'],
            ['module_id' => $m2, 'question' => 'Apa fungsi dari DOM (Document Object Model) dalam JavaScript?', 'option_a' => 'DOM adalah database untuk menyimpan data pengguna secara permanen.', 'option_b' => 'DOM adalah bahasa pemrograman baru pengganti JavaScript.', 'option_c' => 'DOM merupakan representasi struktur halaman web (HTML/XML) sebagai objek yang dapat diakses dan dimanipulasi oleh JavaScript.', 'option_d' => 'DOM digunakan khusus untuk melakukan styling halaman web menggantikan CSS.', 'correct_answer' => 'C'],
            ['module_id' => $m2, 'question' => 'Sintaks mana yang paling tepat untuk mengambil (memilih) elemen HTML yang memiliki atribut id="tombol-login"?', 'option_a' => 'document.getElementByName("tombol-login");', 'option_b' => 'document.getElementById("tombol-login");', 'option_c' => 'document.querySelector(".tombol-login");', 'option_d' => 'document.findId("tombol-login");', 'correct_answer' => 'B'],
            ['module_id' => $m2, 'question' => 'Perbedaan utama antara let dan const dalam mendeklarasikan variabel adalah...', 'option_a' => 'Nilai dari variabel let dapat diubah/di-reassign setelah deklarasi awal, sedangkan variabel const nilainya tetap/konstan.', 'option_b' => 'Variabel let hanya bisa menyimpan angka, sedangkan const hanya bisa menyimpan teks.', 'option_c' => 'Variabel const nilainya dapat diubah, sedangkan let nilainya tetap.', 'option_d' => 'Keduanya tidak memiliki perbedaan fungsi di JavaScript modern.', 'correct_answer' => 'A'],
            ['module_id' => $m2, 'question' => 'Apa hasil dari eksekusi kode berikut: typeof "PahamDulu";?', 'option_a' => 'variable', 'option_b' => 'object', 'option_c' => 'string', 'option_d' => 'boolean', 'correct_answer' => 'C'],
            ['module_id' => $m2, 'question' => 'Di JavaScript, blok kode mana yang akan dieksekusi berulang-ulang selama kondisi tertentu bernilai true?', 'option_a' => 'if statement', 'option_b' => 'switch statement', 'option_c' => 'function', 'option_d' => 'while loop', 'correct_answer' => 'D'],
            ['module_id' => $m2, 'question' => 'Jika kamu memiliki array: const buah = ["Apel", "Mangga", "Jeruk"];, bagaimana cara mengakses elemen "Mangga"?', 'option_a' => 'buah[0]', 'option_b' => 'buah[1]', 'option_c' => 'buah[2]', 'option_d' => 'buah["Mangga"]', 'correct_answer' => 'B'],
            ['module_id' => $m2, 'question' => 'Metode array manakah yang digunakan untuk menambahkan elemen baru ke bagian akhir (ujung) dari sebuah array?', 'option_a' => '.shift()', 'option_b' => '.unshift()', 'option_c' => '.push()', 'option_d' => '.pop()', 'correct_answer' => 'C'],
            ['module_id' => $m2, 'question' => 'Apa fungsi utama dari sebuah function di JavaScript?', 'option_a' => 'Untuk menghapus data dari database.', 'option_b' => 'Membungkus sekumpulan blok kode yang dapat dipanggil atau digunakan kembali berkali-kali.', 'option_c' => 'Untuk mendeklarasikan variabel global.', 'option_d' => 'Untuk memformat teks HTML.', 'correct_answer' => 'B'],
            ['module_id' => $m2, 'question' => 'Sintaks mana yang benar untuk mendefinisikan sebuah function bernama hitungSkor?', 'option_a' => 'function hitungSkor() { ... }', 'option_b' => 'create function hitungSkor() { ... }', 'option_c' => 'function = hitungSkor() { ... }', 'option_d' => 'function:hitungSkor() { ... }', 'correct_answer' => 'A'],
            ['module_id' => $m2, 'question' => 'Dalam event handling JavaScript, method apa yang digunakan untuk "mendengarkan" ketika sebuah elemen diklik, lalu menjalankan suatu fungsi?', 'option_a' => 'element.listenClick()', 'option_b' => 'element.addEventListener("click", fungsi)', 'option_c' => 'element.onHover(fungsi)', 'option_d' => 'element.addClickEvent(fungsi)', 'correct_answer' => 'B'],
            ['module_id' => $m2, 'question' => 'Apa yang dimaksud dengan "Arrow Function" di JavaScript (ES6)?', 'option_a' => 'Fungsi khusus untuk membuat animasi panah (arrow) di canvas HTML5.', 'option_b' => 'Cara yang lebih panjang dan rumit untuk menulis fungsi tradisional.', 'option_c' => 'Sintaks yang lebih ringkas dan modern untuk menulis ekspresi fungsi menggunakan simbol =>.', 'option_d' => 'Fungsi bawaan yang hanya bisa menangani operasi matematika.', 'correct_answer' => 'C'],
            ['module_id' => $m2, 'question' => 'Tipe data struktur mana yang digunakan untuk menyimpan kumpulan pasangan "kunci-nilai" (key-value pairs) di JavaScript?', 'option_a' => 'Number', 'option_b' => 'Boolean', 'option_c' => 'Array', 'option_d' => 'Object', 'correct_answer' => 'D'],
            ['module_id' => $m2, 'question' => 'Jika terdapat objek const user = { nama: "Budi", role: "admin" };, bagaimana cara mengakses nilai "admin"?', 'option_a' => 'user[1]', 'option_b' => 'user.role', 'option_c' => 'user("role")', 'option_d' => 'user->role', 'correct_answer' => 'B'],
            ['module_id' => $m2, 'question' => 'Operator manakah yang merupakan operator logika "AND" di JavaScript?', 'option_a' => '||', 'option_b' => '!', 'option_c' => '&&', 'option_d' => '==', 'correct_answer' => 'C'],
            ['module_id' => $m2, 'question' => 'Apa tujuan dari perintah return di dalam sebuah function?', 'option_a' => 'Menghentikan proses pengulangan (loop).', 'option_b' => 'Mencetak hasil ke layar pengguna (seperti console.log).', 'option_c' => 'Menghentikan eksekusi function dan mengembalikan sebuah nilai spesifik ke pemanggil fungsi tersebut.', 'option_d' => 'Mengembalikan pengguna ke halaman web sebelumnya.', 'correct_answer' => 'C'],
            ['module_id' => $m2, 'question' => 'Metode array .map() berfungsi untuk...', 'option_a' => 'Mencari lokasi koordinat elemen HTML di layar.', 'option_b' => 'Membuat array baru dengan memodifikasi/memproses setiap elemen array lama sesuai dengan fungsi yang diberikan.', 'option_c' => 'Menghapus semua elemen dalam array.', 'option_d' => 'Menggabungkan dua array menjadi satu string.', 'correct_answer' => 'B'],
            ['module_id' => $m2, 'question' => 'Perhatikan kode berikut: const x = "10"; const y = 5; console.log(x + y);. Apa hasil (output) di console?', 'option_a' => '15 (sebagai Number)', 'option_b' => '105 (sebagai String)', 'option_c' => 'undefined', 'option_d' => 'NaN (Not a Number)', 'correct_answer' => 'B'],
            ['module_id' => $m2, 'question' => 'Untuk mengubah struktur atau teks di dalam suatu tag HTML menggunakan JavaScript, properti DOM apa yang paling sering digunakan?', 'option_a' => '.innerHTML', 'option_b' => '.changeText', 'option_c' => '.replaceHTML', 'option_d' => '.innerStyling', 'correct_answer' => 'A'],
            ['module_id' => $m2, 'question' => 'Apa fungsi dari method JSON.parse() di JavaScript?', 'option_a' => 'Mengubah objek JavaScript menjadi string berformat JSON.', 'option_b' => 'Menghapus data JSON yang tidak valid.', 'option_c' => 'Mengubah string berformat JSON menjadi objek JavaScript (Object/Array).', 'option_d' => 'Mengirimkan data JSON ke server API.', 'correct_answer' => 'C'],
            ['module_id' => $m2, 'question' => 'Kata kunci (keyword) apa yang digunakan di JavaScript untuk menangani potensi error/kesalahan pada blok kode tertentu agar program tidak langsung berhenti?', 'option_a' => 'catch...error', 'option_b' => 'try...catch', 'option_c' => 'stop...resume', 'option_d' => 'if...else error', 'correct_answer' => 'B'],

            // Modul 3
            ['module_id' => $m3, 'question' => 'Apa pendekatan utama (paradigm) yang digunakan oleh framework Tailwind CSS?', 'option_a' => 'Component-First (berbasis komponen siap pakai)', 'option_b' => 'Utility-First (berbasis class utilitas kecil)', 'option_c' => 'Object-Oriented (berorientasi objek)', 'option_d' => 'Inline Styling (menggunakan style bawaan tag HTML)', 'correct_answer' => 'B'],
            ['module_id' => $m3, 'question' => 'Sesuai dengan desain "The Dark Bento Grid" PahamDulu, class manakah di Tailwind CSS yang digunakan untuk membuat sudut elemen menjadi sangat membulat (extra rounded)?', 'option_a' => 'border-radius-lg', 'option_b' => 'corner-round', 'option_c' => 'rounded-2xl', 'option_d' => 'circle-border', 'correct_answer' => 'C'],
            ['module_id' => $m3, 'question' => 'Class flex di Tailwind CSS berfungsi untuk...', 'option_a' => 'Menerapkan properti CSS display: flex;', 'option_b' => 'Membuat font menjadi fleksibel menyesuaikan layar.', 'option_c' => 'Menghilangkan elemen dari tampilan (display: none;).', 'option_d' => 'Memberikan animasi melentur (bouncing) pada tombol.', 'correct_answer' => 'A'],
            ['module_id' => $m3, 'question' => 'Untuk memberikan margin atas (margin-top) sebesar 1rem (16px), class Tailwind apa yang harus ditulis?', 'option_a' => 'm-top-4', 'option_b' => 'mt-16', 'option_c' => 'margin-t-4', 'option_d' => 'mt-4', 'correct_answer' => 'D'],
            ['module_id' => $m3, 'question' => 'Jika kamu ingin menggunakan warna aksen Cyber Neon (Electric Lime) pada sebuah teks secara kustom (arbitrary value) di Tailwind, penulisan yang benar adalah:', 'option_a' => 'text-[CCFF00]', 'option_b' => 'text-[#CCFF00]', 'option_c' => 'color-[#CCFF00]', 'option_d' => 'text-neon', 'correct_answer' => 'B'],
            ['module_id' => $m3, 'question' => 'Awalan (prefix) apa yang digunakan di Tailwind CSS untuk menerapkan gaya secara spesifik hanya pada layar berukuran besar (desktop)?', 'option_a' => 'large:', 'option_b' => 'desktop:', 'option_c' => 'lg:', 'option_d' => 'l:', 'correct_answer' => 'C'],
            ['module_id' => $m3, 'question' => 'Class apa yang digunakan untuk menyembunyikan sebuah elemen sepenuhnya dari halaman web (display: none)?', 'option_a' => 'invisible', 'option_b' => 'hide', 'option_c' => 'hidden', 'option_d' => 'none', 'correct_answer' => 'C'],
            ['module_id' => $m3, 'question' => 'File konfigurasi utama di mana kamu bisa mengatur font, palet warna, dan tema kustom untuk Tailwind bernama...', 'option_a' => 'tailwind.config.js', 'option_b' => 'tailwind.settings.js', 'option_c' => 'config.tailwind.json', 'option_d' => 'tailwind.setup.js', 'correct_answer' => 'A'],
            ['module_id' => $m3, 'question' => 'Untuk membuat teks rata tengah (center alignment), class Tailwind yang digunakan adalah...', 'option_a' => 'align-center', 'option_b' => 'text-center', 'option_c' => 'center-text', 'option_d' => 'text-middle', 'correct_answer' => 'B'],
            ['module_id' => $m3, 'question' => 'Class w-full pada Tailwind CSS setara dengan aturan CSS murni...', 'option_a' => 'width: auto;', 'option_b' => 'width: 100vw;', 'option_c' => 'width: 100%;', 'option_d' => 'width: max-content;', 'correct_answer' => 'C'],
            ['module_id' => $m3, 'question' => 'Bagaimana cara memberikan jarak di bagian dalam (padding) pada semua sisi elemen sebesar 8px (0.5rem)?', 'option_a' => 'p-2', 'option_b' => 'pd-8', 'option_c' => 'pad-2', 'option_d' => 'p-8', 'correct_answer' => 'A'],
            ['module_id' => $m3, 'question' => 'Class apa yang harus ditambahkan pada elemen induk (container) untuk membuat sistem Grid dengan 3 kolom yang sama besar?', 'option_a' => 'grid cols-3', 'option_b' => 'grid-template-3', 'option_c' => 'grid grid-cols-3', 'option_d' => 'grid-3', 'correct_answer' => 'C'],
            ['module_id' => $m3, 'question' => 'Untuk membuat sebuah teks menjadi tebal (bold), class Tailwind yang benar adalah...', 'option_a' => 'text-bold', 'option_b' => 'font-bold', 'option_c' => 'weight-bold', 'option_d' => 'bold', 'correct_answer' => 'B'],
            ['module_id' => $m3, 'question' => 'Direktif Tailwind apa yang dapat digunakan di file CSS kustom untuk menyalin (menggabungkan) beberapa utility class ke dalam satu nama class baru?', 'option_a' => '@extend', 'option_b' => '@include', 'option_c' => '@apply', 'option_d' => '@tailwind-class', 'correct_answer' => 'C'],
            ['module_id' => $m3, 'question' => 'Di dalam elemen Flexbox atau Grid, class apa yang digunakan untuk memberikan jarak ruang kosong di antara item-item di dalamnya?', 'option_a' => 'space', 'option_b' => 'gap', 'option_c' => 'margin-between', 'option_d' => 'distance', 'correct_answer' => 'B'],
            ['module_id' => $m3, 'question' => 'Bagaimana cara menerapkan efek bayangan (shadow) berukuran sedang pada sebuah kartu materi?', 'option_a' => 'shadow-md', 'option_b' => 'box-shadow-md', 'option_c' => 'drop-shadow-md', 'option_d' => 'shadow-medium', 'correct_answer' => 'A'],
            ['module_id' => $m3, 'question' => 'Class h-screen pada Tailwind CSS berfungsi untuk membuat tinggi sebuah elemen menjadi...', 'option_a' => '100% dari tinggi elemen pembungkusnya', 'option_b' => 'Sepenuh tinggi layar (100vh)', 'option_c' => 'Tinggi otomatis menyesuaikan konten', 'option_d' => 'Maksimal 1000px', 'correct_answer' => 'B'],
            ['module_id' => $m3, 'question' => 'Untuk memposisikan sebuah elemen kotak agar berada tepat di tengah-tengah secara horizontal, class margin apa yang sering digunakan?', 'option_a' => 'm-center', 'option_b' => 'mx-auto', 'option_c' => 'my-auto', 'option_d' => 'align-center', 'correct_answer' => 'B'],
            ['module_id' => $m3, 'question' => 'Jika kamu ingin memposisikan elemen secara absolute (misalnya ikon gembok kuis yang terkunci), class yang kamu gunakan adalah...', 'option_a' => 'pos-absolute', 'option_b' => 'absolute', 'option_c' => 'position-absolute', 'option_d' => 'abs', 'correct_answer' => 'B'],
            ['module_id' => $m3, 'question' => 'Class apa yang mengatur warna latar belakang menjadi hitam murni di Tailwind?', 'option_a' => 'bg-black', 'option_b' => 'background-black', 'option_c' => 'color-black', 'option_d' => 'bg-color-black', 'correct_answer' => 'A'],
            ['module_id' => $m3, 'question' => 'Untuk mengubah warna tombol hanya pada saat kursor mouse diarahkan ke atasnya, prefix (awalan) apa yang harus digunakan?', 'option_a' => 'focus:', 'option_b' => 'active:', 'option_c' => 'hover:', 'option_d' => 'onHover:', 'correct_answer' => 'C'],
            ['module_id' => $m3, 'question' => 'Penggunaan class justify-center pada elemen flex container akan mengakibatkan...', 'option_a' => 'Item-item tersebar merata.', 'option_b' => 'Item-item diratakan ke tengah sejajar dengan sumbu utama (main axis).', 'option_c' => 'Mengubah arah susunan dari baris menjadi kolom.', 'option_d' => 'Item-item diratakan ke tengah sejajar dengan sumbu silang (cross axis).', 'correct_answer' => 'B'],
            ['module_id' => $m3, 'question' => 'Untuk mengubah tingkat transparansi (opacity) pada teks menjadi 50%, class yang digunakan adalah...', 'option_a' => 'text-opacity-50', 'option_b' => 'opacity-text-50', 'option_c' => 'text-transparent-50', 'option_d' => 'text-50', 'correct_answer' => 'A'],
            ['module_id' => $m3, 'question' => 'Apa fungsi dari class z-10?', 'option_a' => 'Mengubah ukuran font menjadi 10.', 'option_b' => 'Mengatur tingkat tumpukan elemen (z-index) sebesar 10.', 'option_c' => 'Melakukan zoom in pada elemen.', 'option_d' => 'Memberikan margin sumbu-Z.', 'correct_answer' => 'B'],
            ['module_id' => $m3, 'question' => 'Salah satu fitur andalan untuk tampilan Glassmorphism adalah efek kaca buram. Class Tailwind apa yang menciptakan efek ini pada elemen yang memiliki background transparan?', 'option_a' => 'blur-md', 'option_b' => 'backdrop-blur-md', 'option_c' => 'glass-md', 'option_d' => 'filter-blur-md', 'correct_answer' => 'B'],
        ];

        foreach ($questions as $q) {
            Quiz::create($q);
        }
    }
}
